### ISSUE TITLE
syntax errors

### ISSUE THREAD

**Issue by CharlieJo42** [CharlieJo42/Unit2CodingProject#2]
I am trying to run the command _psql -d water_logged -f db/migrations/20200812446-create-user-table.sql_  but it is catching some sort of syntax error.

**Attempts:**

-Changed ( )  to { }
-Removed empty spaces between paranthesis/brackets and the code
-Removed all brackets entirely (against better judgment), which only triggered a new error with the first line in the table.
-Made "id", "ID", but to no avail. 

**Only unusual thing outside of the lecture video is that VSCode prompted me to download "Microsoft SQL Server (mssql)" as a VSCode extension. I haven't done it yet; should I do so?**

> 

> charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:7: ERROR:  syntax error at or near ")"
> > LINE 6: );
> >         ^
> > charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:6: ERROR:  syntax error at or near ")"
> > LINE 6: );
> >         ^
> > charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:6: ERROR:  syntax error at or near "{"
> > LINE 1: CREATE TABLE IF NOT EXISTS user_table {
> >                                               ^
> > charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:6: ERROR:  syntax error at or near "{"
> > LINE 1: CREATE TABLE IF NOT EXISTS user_table{
> >                                              ^
> > charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:6: ERROR:  syntax error at or near "{"
> > LINE 1: CREATE TABLE IF NOT EXISTS user_table {
> >                                               ^
> > charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:5: ERROR:  syntax error at or near "id"
> > LINE 2:     id SERIAL PRIMARY KEY,
> >             ^
> > charliejo42@StarkIndustries:~/Desktop/Unit2Coding$ psql -d water_logged -f db/migrations/20200812446-create-user-table.sql 
> > psql:db/migrations/20200812446-create-user-table.sql:5: ERROR:  syntax error at or near "ID"
> > LINE 2:     ID SERIAL PRIMARY KEY,
>

**Comment by jlr7245** [comment]
see comment here! you have an extra comma but parens are the correct way to go about it. don't worry abt the mysql extension, you will be fine without. https://github.com/CharlieJo42/Unit2CodingProject/commit/db673511145b151212903c4c4008bc32437b57a2#r41421873
